import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-admin';
import { cookies } from 'next/headers';

// GET - Fetch active UMKM (public)
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const kategori = searchParams.get('kategori');
    const slug = searchParams.get('slug');
    const id = searchParams.get('id');

    let query = supabaseAdmin
      .from('umkm')
      .select('*')
      .eq('is_active', true)
      .order('created_at', { ascending: false });

    if (slug) {
      query = query.eq('slug', slug);
    }

    if (id) {
      query = query.eq('id', id);
    }

    if (kategori) {
      query = query.eq('kategori', kategori);
    }

    const { data, error } = await query;

    if (error) throw error;

    return NextResponse.json({ data });
  } catch (error) {
    console.error('Error fetching UMKM:', error);
    return NextResponse.json(
      { error: 'Failed to fetch UMKM' },
      { status: 500 }
    );
  }
}

// POST - Add new UMKM (admin only)
export async function POST(request: NextRequest) {
  try {
    // Check admin session
    const cookieStore = await cookies();
    const adminSession = cookieStore.get('admin_session');

    if (!adminSession) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const {
      nama_usaha,
      kategori,
      deskripsi,
      nama_pemilik,
      nomor_telepon,
      email,
      alamat,
      foto_url,
      foto_path,
      whatsapp,
      instagram,
      jam_operasional,
      harga_range,
      is_featured = false,
      tahun_berdiri,
    } = body;

    if (!nama_usaha || !kategori || !nama_pemilik) {
      return NextResponse.json(
        { error: 'Nama usaha, kategori, and nama pemilik are required' },
        { status: 400 }
      );
    }

    // Insert new UMKM (slug auto-generated by trigger)
    const { data, error } = await supabaseAdmin
      .from('umkm')
      .insert({
        nama_usaha,
        kategori,
        deskripsi,
        nama_pemilik,
        nomor_telepon,
        email,
        alamat,
        foto_url,
        foto_path,
        whatsapp,
        instagram,
        jam_operasional,
        harga_range,
        is_featured,
        tahun_berdiri,
        views_count: 0,
        created_by: adminSession.value,
        updated_by: adminSession.value,
      } as any)
      .select()
      .single();

    if (error) throw error;

    return NextResponse.json({ 
      success: true, 
      data,
      message: 'UMKM added successfully' 
    });
  } catch (error) {
    console.error('Error adding UMKM:', error);
    return NextResponse.json(
      { error: 'Failed to add UMKM' },
      { status: 500 }
    );
  }
}

// PUT - Update UMKM (admin only)
export async function PUT(request: NextRequest) {
  try {
    // Check admin session
    const cookieStore = await cookies();
    const adminSession = cookieStore.get('admin_session');

    if (!adminSession) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { id, ...updateData } = body;

    if (!id) {
      return NextResponse.json(
        { error: 'UMKM ID is required' },
        { status: 400 }
      );
    }

    // Update UMKM
    const { data, error } = await supabaseAdmin
      .from('umkm')
      // @ts-expect-error - Supabase type issue with update
      .update({
        ...updateData,
        updated_by: adminSession.value,
      } as any)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;

    return NextResponse.json({ 
      success: true, 
      data,
      message: 'UMKM updated successfully' 
    });
  } catch (error) {
    console.error('Error updating UMKM:', error);
    return NextResponse.json(
      { error: 'Failed to update UMKM' },
      { status: 500 }
    );
  }
}

// DELETE - Delete UMKM (admin only - soft delete)
export async function DELETE(request: NextRequest) {
  try {
    // Check admin session
    const cookieStore = await cookies();
    const adminSession = cookieStore.get('admin_session');

    if (!adminSession) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json(
        { error: 'UMKM ID is required' },
        { status: 400 }
      );
    }

    // Soft delete by setting is_active to false
    const { error } = await supabaseAdmin
      .from('umkm')
      // @ts-expect-error - Supabase type issue with update
      .update({ is_active: false } as any)
      .eq('id', id);

    if (error) throw error;

    return NextResponse.json({ 
      success: true,
      message: 'UMKM deleted successfully' 
    });
  } catch (error) {
    console.error('Error deleting UMKM:', error);
    return NextResponse.json(
      { error: 'Failed to delete UMKM' },
      { status: 500 }
    );
  }
}
