import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-admin';
import { cookies } from 'next/headers';

// GET - Fetch published news/events (public)
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const category = searchParams.get('category');
    const limit = searchParams.get('limit');

    let query = supabaseAdmin
      .from('news_events')
      .select('*')
      .eq('is_published', true)
      .order('published_at', { ascending: false });

    if (category) {
      query = query.eq('category', category);
    }

    if (limit) {
      query = query.limit(parseInt(limit));
    }

    const { data, error } = await query;

    if (error) throw error;

    return NextResponse.json({ data });
  } catch (error) {
    console.error('Error fetching news:', error);
    return NextResponse.json(
      { error: 'Failed to fetch news' },
      { status: 500 }
    );
  }
}

// POST - Add new news/event (admin only)
export async function POST(request: NextRequest) {
  try {
    // Check admin session
    const cookieStore = await cookies();
    const adminSession = cookieStore.get('admin_session');

    if (!adminSession) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const {
      category,
      title,
      description,
      content,
      image_url,
      image_path,
      thumbnail_url,
      event_date,
      event_time_start,
      event_time_end,
      event_location,
      is_published = true,
      is_featured = false,
    } = body;

    if (!category || !title || !content) {
      return NextResponse.json(
        { error: 'Category, title, and content are required' },
        { status: 400 }
      );
    }

    // Insert new news/event (slug auto-generated by trigger)
    const { data, error } = await supabaseAdmin
      .from('news_events')
      .insert({
        category,
        title,
        description,
        content,
        image_url,
        image_path,
        thumbnail_url,
        event_date,
        event_time_start,
        event_time_end,
        event_location,
        is_published,
        is_featured,
        views_count: 0,
        created_by: adminSession.value,
        updated_by: adminSession.value,
      } as any)
      .select()
      .single();

    if (error) throw error;

    return NextResponse.json({ 
      success: true, 
      data,
      message: 'News/Event added successfully' 
    });
  } catch (error) {
    console.error('Error adding news:', error);
    return NextResponse.json(
      { error: 'Failed to add news' },
      { status: 500 }
    );
  }
}

// PUT - Update news/event (admin only)
export async function PUT(request: NextRequest) {
  try {
    // Check admin session
    const cookieStore = await cookies();
    const adminSession = cookieStore.get('admin_session');

    if (!adminSession) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { id, ...updateData } = body;

    if (!id) {
      return NextResponse.json(
        { error: 'News ID is required' },
        { status: 400 }
      );
    }

    // Update news/event
    const { data, error } = await supabaseAdmin
      .from('news_events')
      // @ts-expect-error - Supabase type issue with update
      .update({
        ...updateData,
        updated_by: adminSession.value,
      } as any)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;

    return NextResponse.json({ 
      success: true, 
      data,
      message: 'News/Event updated successfully' 
    });
  } catch (error) {
    console.error('Error updating news:', error);
    return NextResponse.json(
      { error: 'Failed to update news' },
      { status: 500 }
    );
  }
}

// DELETE - Delete news/event (admin only)
export async function DELETE(request: NextRequest) {
  try {
    // Check admin session
    const cookieStore = await cookies();
    const adminSession = cookieStore.get('admin_session');

    if (!adminSession) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const { searchParams } = new URL(request.url);
    const newsId = searchParams.get('id');

    if (!newsId) {
      return NextResponse.json(
        { error: 'News ID is required' },
        { status: 400 }
      );
    }

    // Soft delete (unpublish)
    const { error } = await supabaseAdmin
      .from('news_events')
      // @ts-expect-error - Supabase type issue with update
      .update({ is_published: false } as any)
      .eq('id', newsId);

    if (error) throw error;

    return NextResponse.json({ 
      success: true,
      message: 'News/Event deleted successfully' 
    });
  } catch (error) {
    console.error('Error deleting news:', error);
    return NextResponse.json(
      { error: 'Failed to delete news' },
      { status: 500 }
    );
  }
}
